apiVersion: tekton.dev/v1beta1
kind: StepAction
metadata:
  name: export-resources-record
spec:
  description: |
    This is a step to pass the testing resources to result
  image: $(params.container-image)
  workingDir: /
  params:
    - name: container-image
    - name: output-volume
    - name: cluster-profile
  volumeMounts:
    - name: $(params.output-volume)
      mountPath: /tests/output
  script: |
    #!/bin/bash
    cat /rosa/tests/output/$(params.cluster-profile)/konflux_resources.json > $(results.konflux-resources-json.path)
