apiVersion: tekton.dev/v1beta1
kind: StepAction
metadata:
  name: export-resources-record
spec:
  description: |
    This is a step to pass the testing resources to result
  image: $(params.container-image)
  workingDir: /
  params:
    - name: container-image
    - name: output-volume
    - name: cluster-profile
    - name: konflux-resources-json
  volumeMounts:
    - name: $(params.output-volume)
      mountPath: /tests/output
  env:
    - name: KonfluxResourcesJson
      value: $(params.konflux-resources-json)
    - name: TEST_PROFILE
      value: $(params.cluster-profile)
  script: |
    #!/bin/bash
    cat /rosa/tests/output/$(TEST_PROFILE)/konflux_resources.json > $(KonfluxResourcesJson)